dbtlearn:
  outputs:
    dev:
      account: xjilcwc-dl57311
      database: AIRBNB
      password: dbtPassword123
      role: transform
      schema: dev
      threads: 1
      type: snowflake
      user: dbt
      warehouse: COMPUTE_WH
  target: dev